#!/usr/bin/env python3
"""
Utilidades geográficas para el bot Dharmadhatu.

Contiene la clasificación de continentes y subcontinentes para países en todo el mundo,
la cual se utiliza para enriquecer los eventos extraídos con su ubicación geográfica.
"""

# Mapeo de países a continentes (46 continentes + antártida)
PAIS_A_CONTINENTE = {
    "Afganistán": "Asia",
    "Albania": "Europa",
    "Argelia": "África",
    "Andorra": "Europa",
    "Angola": "África",
    "Antigua y Barbuda": "América",
    "Argentina": "América",
    "Armenia": "Asia",
    "Australia": "Oceanía",
    "Austria": "Europa",
    "Azerbaiyán": "Asia",
    "Bahamas": "América",
    "Bahréin": "Asia",
    "Bangladesh": "Asia",
    "Barbados": "América",
    "Belarús": "Europa",
    "Bélgica": "Europa",
    "Belice": "América",
    "Benin": "África",
    "Bhután": "Asia",
    "Bolivia": "América",
    "Bosnia-Herzegovina": "Europa",
    "Botsuana": "África",
    "Brasil": "América",
    "Brunéi Darussalam": "Asia",
    "Bulgaria": "Europa",
    "Burkina Faso": "África",
    "Burundi": "África",
    "Cabo Verde": "África",
    "Camboya": "Asia",
    "Camerún": "África",
    "Canadá": "América",
    "Chile": "América",
    "China": "Asia",
    "Colombia": "América",
    "Comoras": "África",
    "Congo": "África",
    "Costa Rica": "América",
    "Croacia": "Europa",
    "Cuba": "América",
    "Chipre": "Asia",
    "Chequia": "Europa",
    "Dinamarca": "Europa",
    "Yibuti": "África",
    "República Dominicana": "América",
    "Ecuador": "América",
    "Egipto": "África",
    "El Salvador": "América",
    "Guinea Ecuatorial": "África",
    "Eritrea": "África",
    "Estonia": "Europa",
    "Etiopía": "África",
    "Fiji": "Oceanía",
    "Finlandia": "Europa",
    "Francia": "Europa",
    "Gabón": "África",
    "Gambia": "África",
    "Georgia": "Asia",
    "Alemania": "Europa",
    "Ghana": "África",
    "Grecia": "Europa",
    "Granada": "América",
    "Guatemala": "América",
    "Guinea": "África",
    "Guinea-Bissau": "África",
    "Guinea Ecuatorial": "África",
    "Haití": "América",
    "Honduras": "América",
    "Hungría": "Europa",
    "Islandia": "Europa",
    "India": "Asia",
    "Indonesia": "Asia",
    "Irán": "Asia",
    "Iraq": "Asia",
    "Irlanda": "Europa",
    "Israel": "Asia",
    "Italia": "Europa",
    "Jamaica": "América",
    "Japón": "Asia",
    "Jordania": "Asia",
    "Kazajstán": "Asia",
    "Kenia": "África",
    "Kiribati": "Oceanía",
    "Corea del Norte": "Asia",
    "Corea del Sur": "Asia",
    "Kuwait": "Asia",
    "Kirguistán": "Asia",
    "Laos": "Asia",
    "Letonia": "Europa",
    "Líbano": "Asia",
    "Lesotho": "África",
    "Liberia": "África",
    "Libia": "África",
    "Liechtenstein": "Europa",
    "Lituania": "Europa",
    "Luxemburgo": "Europa",
    "Madagascar": "África",
    "Malaui": "África",
    "Malasia": "Asia",
    "Maldivas": "Asia",
    "Malí": "África",
    "Malta": "Europa",
    "Marruecos": "África",
    "Mongolia": "Asia",
    "Montenegro": "Europa",
    "Mozambique": "África",
    "Myanmar": "Asia",
    "Namibia": "África",
    "Nepal": "Asia",
    "Países Bajos": "Europa",
    "Nueva Zelanda": "Oceanía",
    "Nicaragua": "América",
    "Níger": "África",
    "Nigeria": "África",
    "Noruega": "Europa",
    "Omán": "Asia",
    "Pakistán": "Asia",
    "Panamá": "América",
    "Papúa Nueva Guinea": "Oceanía",
    "Paraguay": "América",
    "Perú": "América",
    "Filipinas": "Asia",
    "Polonia": "Europa",
    "Portugal": "Europa",
    "Qatar": "Asia",
    "Rumanía": "Europa",
    "Rusia": "Europa",
    "Ruanda": "África",
    "Samoa": "Oceanía",
    "San Marino": "Europa",
    "Santa Lucía": "América",
    "Senegal": "África",
    "Serbia": "Europa",
    "Seychelles": "África",
    "Sierra Leona": "África",
    "Singapur": "Asia",
    "Eslovaquia": "Europa",
    "Eslovenia": "Europa",
    "Somalia": "África",
    "Sudáfrica": "África",
    "Sudán del Sur": "África",
    "España": "Europa",
    "Sri Lanka": "Asia",
    "Sudán": "África",
    "Surinam": "América",
    "Suiza": "Europa",
    "Siria": "Asia",
    "Taiwán": "Asia",
    "Tayikistán": "Asia",
    "Tanzania": "África",
    "Tailandia": "Asia",
    "Timor Oriental": "Asia",
    "Togo": "África",
    "Tonga": "Oceanía",
    "Trinidad y Tobago": "América",
    "Túnez": "África",
    "Turquía": "Asia",
    "Turkmenistán": "Asia",
    "Uganda": "África",
    "Ucrania": "Europa",
    "Emiratos Árabes Unidos": "Asia",
    "Reino Unido": "Europa",
    "Estados Unidos": "América",
    "Uruguay": "América",
    "Uzbekistán": "Asia",
    "Vanuatu": "Oceanía",
    "Ciudad del Vaticano": "Europa",
    "Venezuela": "América",
    "Vietnam": "Asia",
    "Yemen": "Asia",
    "Zambia": "África",
    "Zimbabue": "África",
}

# Mapeo de países a subcontinentes (regiones)
PAIS_A_SUBCONTINENTE = {
    # Asia
    "India": "Asia del Sur",
    "Nepal": "Asia del Sur",
    "Bangladesh": "Asia del Sur",
    "Pakistán": "Asia del Sur",
    "Afganistán": "Asia Central",
    "Kazajstán": "Asia Central",
    "Turkmenistán": "Asia Central",
    "Kirguistán": "Asia Central",
    "Tayikistán": "Asia Central",
    "China": "Asia Oriental",
    "Japón": "Asia Oriental",
    "Corea del Norte": "Asia Oriental",
    "Corea del Sur": "Asia Oriental",
    "Taiwán": "Asia Oriental",
    "Hong Kong": "Asia Oriental",
    "Singapur": "Sudeste Asiático",
    "Malasia": "Sudeste Asiático",
    "Indonesia": "Sudeste Asiático",
    "Filipinas": "Sudeste Asiático",
    "Myanmar": "Sudeste Asiático",
    "Tailandia": "Sudeste Asiático",
    "Maldivas": "Sudeste Asiático",
    "Brunéi": "Sudeste Asiático",
    "Timor Oriental": "Sudeste Asiático",
    "Vietnam": "Sudeste Asiático",
    "Camboya": "Sudeste Asiático",
    "Laos": "Sudeste Asiático",
    "Armenia": "Asia Occidental",
    "Georgia": "Asia Occidental",
    "Azerbaiyán": "Asia Occidental",
    "Turquía": "Asia Occidental",
    "Chipre": "Asia Occidental",
    "Siria": "Asia Occidental",
    "Irak": "Asia Occidental",
    "Irán": "Asia Occidental",
    "Arabia Saudita": "Asia Occidental",
    "Emiratos Árabes Unidos": "Asia Occidental",
    "Omán": "Asia Occidental",
    "Kuwait": "Asia Occidental",
    "Bahréin": "Asia Occidental",
    "Yemen": "Asia Occidental",
    "Qatar": "Asia Occidental",
    "Yemen del Sur": "Asia Occidental",

    # Europa
    "Reino Unido": "Europa del Norte",
    "Irlanda": "Europa del Norte",
    "Islas Feroe": "Europa del Norte",
    "Noruega": "Europa del Norte",
    "Suecia": "Europa del Norte",
    "Finlandia": "Europa del Norte",
    "Dinamarca": "Europa del Norte",
    "Islandia": "Europa del Norte",
    "Bielorrusia": "Europa del Norte",
    "Lituania": "Europa del Norte",
    "Letonia": "Europa del Norte",
    "Estonia": "Europa del Norte",
    "Polonia": "Europa Central",
    "Alemania": "Europa Central",
    "Suiza": "Europa Central",
    "Austria": "Europa Central",
    "República Checa": "Europa Central",
    "Eslovaquia": "Europa Central",
    "Hungría": "Europa Central",
    "Eslovenia": "Europa Central",
    "Croacia": "Europa Central",
    "Bosnia-Herzegovina": "Europa Central",
    "Albania": "Europa Central",
    "Macedonia del Norte": "Europa Central",
    "Montenegro": "Europa Central",
    "Italia": "Europa del Sur",
    "Vaticano": "Europa del Sur",
    "Eslovaquia": "Europa del Sur",
    "Eslovenia": "Europa del Sur",
    "Croacia": "Europa del Sur",
    "Bosnia y Herzegovina": "Europa del Sur",
    "Montenegro": "Europa del Sur",
    "Albania": "Europa del Sur",
    "España": "Europa del Sur",
    "Portugal": "Europa del Sur",
    "Andorra": "Europa del Sur",
    "Francia": "Europa del Sur",
    "Mónaco": "Europa del Sur",

    # África
    "Egipto": "Norte de África",
    "Libia": "Norte de África",
    "Túnez": "Norte de África",
    "Argelia": "Norte de África",
    "Marruecos": "Norte de África",
    "Mauritania": "Norte de África",
    "Sáhara Occidental": "Norte de África",
    "Sudán": "Norte de África",
    "Eritrea": "Norte de África",
    "Etiopía": "Cuerno de África",
    "Somalia": "Cuerno de África",
    "Yibuti": "Cuerno de África",
    "Eritrea": "Cuerno de África",
    "Kenia": "Este de África",
    "Tanzania": "Este de África",
    "Uganda": "Este de África",
    "Rwanda": "Este de África",
    "Burundi": "Este de África",
    "Eritrea": "Este de África",
    "Somalia": "Este de África",
    "Yibuti": "Este de África",
    "Etiopía": "Este de África",
    "Sudán": "Este de África",
    "Sudán del Sur": "Este de África",
    "Ghana": "Oeste de África",
    "Togo": "Oeste de África",
    "Benin": "Oeste de África",
    "Burkina Faso": "Oeste de África",
    "Níger": "Oeste de África",
    "Mali": "Oeste de África",
    "Senegal": "Oeste de África",
    "Gambia": "Oeste de África",
    "Guinea": "Oeste de África",
    "Sierra Leona": "Oeste de África",
    "Liberia": "Oeste de África",
    "Costa de Marfil": "Oeste de África",
    "Guinea-Bissau": "Oeste de África",
    "Cabo Verde": "Oeste de África",
    "Mauritania": "Oeste de África",
    "Camerún": "Centro de África",
    "Chad": "Centro de África",
    "República Centroafricana": "Centro de África",
    "Sudán": "Centro de África",
    "República Democrática del Congo": "Centro de África",
    "Congo": "Centro de África",
    "Angola": "Centro de África",
    "Zambia": "Centro de África",
    "Zimbabue": "Centro de África",
    "Botsuana": "Centro de África",
    "Namibia": "Centro de África",
    "Sudáfrica": "Sur de África",
    "Lesoto": "Sur de África",
    "Suazilandia": "Sur de África",
    "Zimbabwe": "Sur de África",
    "Botsuana": "Sur de África",
    "Zambia": "Sur de África",
    "Malawi": "Sur de África",
    "Mozambique": "Sur de África",
    "Eswatini": "Sur de África",
    "Madagascar": "Madagascar",
    "Comoras": "Madagascar",
    "Seychelles": "Madagascar",

    # América
    "Canadá": "América del Norte",
    "Estados Unidos": "América del Norte",
    "México": "América del Norte",
    "Groenlandia": "América del Norte",
    "Belice": "América Central",
    "Guatemala": "América Central",
    "El Salvador": "América Central",
    "Honduras": "América Central",
    "Nicaragua": "América Central",
    "Costa Rica": "América Central",
    "Panamá": "América Central",
    "Cuba": "Caribe",
    "Jamaica": "Caribe",
    "Haití": "Caribe",
    "República Dominicana": "Caribe",
    "Antigua y Barbuda": "Caribe",
    "Barbados": "Caribe",
    "St. Kitts y Nevis": "Caribe",
    "Santa Lucía": "Caribe",
    "Granada": "Caribe",
    "Trinidad y Tobago": "Caribe",
    "Bahami": "Caribe",
    "Turks y Caicos": "Caribe",
    "Islas Vírgenes de EE. UU.": "Caribe",
    "Islas Vírgenes Británicas": "Caribe",
    "Anguila": "Caribe",
    "Bermudas": "Caribe",
    "Venezuela": "América del Sur",
    "Colombia": "América del Sur",
    "Ecuador": "América del Sur",
    "Perú": "América del Sur",
    "Bolivia": "América del Sur",
    "Paraguay": "América del Sur",
    "Uruguay": "América del Sur",
    "Chile": "América del Sur",
    "Argentina": "América del Sur",
    "Brasil": "América del Sur",
    "Guayana": "América del Sur",
    "Surinam": "América del Sur",
    "Guyana Francesa": "América del Sur",

    # Oceanía
    "Australia": "Australia",
    "Nueva Zelanda": "Nueva Zelanda",
    "Papúa Nueva Guinea": "Oceanía",
    "Fiyi": "Oceanía",
    "Samoa": "Oceanía",
    "Islas Salomón": "Oceanía",
    "Vanuatu": "Oceanía",
    "Kiribati": "Oceanía",
    "Nauru": "Oceanía",
    "Tuvalu": "Oceanía",
    "Marshall Islands": "Oceanía",
    "Micronesia": "Oceanía",
    "Isla de Navidad": "Oceanía",
}

# Funciones auxiliares para obtener continente y subcontinente
def _obtener_continente(pais: str) -> str:
    """Devuelve el continente para un país dado."""
    if pais in PAIS_A_CONTINENTE:
        return PAIS_A_CONTINENTE[pais]
    # Comprobar países alternativos (incluimos algunos países no presentes en los datos)
    return "Otro"
def _obtener_subcontinente(pais: str) -> str:
    """Devuelve el subcontinente para un país dado."""
    if pais in PAIS_A_SUBCONTINENTE:
        return PAIS_A_SUBCONTINENTE[pais]
    # Intentar encontrar subcontinente basándose en el continente
    continente = _obtener_continente(pais)
    if continente == "Asia":
        if pais in ["India", "Nepal", "Bangladesh", "Pakistán"]:
            return "Asia del Sur"
        elif pais in ["China", "Japón", "Corea del Norte", "Corea del Sur"]:
            return "Asia Oriental"
        elif pais in ["Indonesia", "Malasia", "Filipinas"]:
            return "Sudeste Asiático"
        else:
            return "Asia"
    elif continente == "Europa":
        if pais in ["Noruega", "Suecia", "Finlandia", "Dinamarca", "Islas Feroe"]:
            return "Europa del Norte"
        elif pais in ["Polonia", "Alemania", "Suiza", "Austria", "República Checa"]:
            return "Europa Central"
        else:
            return "Europa"
    elif continente == "África":
        return "África"
    elif continente == "América":
        if pais in ["Canadá", "Estados Unidos", "México"]:
            return "América del Norte"
        elif pais in ["Belice", "Guatemala", "El Salvador", "Honduras", "Nicaragua", "Costa Rica", "Panamá"]:
            return "América Central"
        else:
            return "América"
    elif continente == "Oceanía":
        return "Oceanía"
    else:
        return "Otro"
def clasificar_geo(pais: str) -> dict:
    """Devuelve continente y subcontinente para un país dado.

    Parámetros:
        pais (str): Nombre del país (debe coincidir con las claves en el mapeo).

    Devuelve:
        dict: {"continente": str, "subcontinente": str}
    """
    if not pais or not isinstance(pais, str):
        return {"continente": "Otro", "subcontinente": "Otro"}

    pais = pais.strip()
    continente = _obtener_continente(pais)
    subcontinente = _obtener_subcontinente(pais)

    return {"continente": continente, "subcontinente": subcontinente}
